# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions
# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow

name: Deno

on:
    push:
        branches: main
    pull_request:
        branches: main

permissions:
    contents: read

jobs:
    test:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4 # https://github.com/actions/checkout
            - uses: denoland/setup-deno@v2 # https://github.com/denoland/setup-deno
              with:
                  deno-version: vx.x.x
            - run: deno lint
            - run: deno fmt --check
            # - run: deno test --allow-all

# https://docs.deno.com/runtime/fundamentals/linting_and_formatting/
# https://docs.deno.com/runtime/fundamentals/testing/
